using SqlParser.Net.Ast.Expression;

using SqlParser.Net.Ast.Visitor;

/// <summary>
/// Automatically generated by testHelper
/// </summary>
public class BaseAstVisitor : IAstVisitor
{
    public virtual SqlExpression VisitSqlAllColumnExpression(SqlAllColumnExpression sqlAllColumnExpression, VisitContext context = null)
    {
        return sqlAllColumnExpression;
    }
    public virtual SqlExpression VisitSqlAllExpression(SqlAllExpression sqlAllExpression, VisitContext context = null)
    {
        return sqlAllExpression;
    }
    public virtual SqlExpression VisitSqlAnyExpression(SqlAnyExpression sqlAnyExpression, VisitContext context = null)
    {
        return sqlAnyExpression;
    }
    public virtual SqlExpression VisitSqlArrayExpression(SqlArrayExpression sqlArrayExpression, VisitContext context = null)
    {
        return sqlArrayExpression;
    }
    public virtual SqlExpression VisitSqlArrayIndexExpression(SqlArrayIndexExpression sqlArrayIndexExpression, VisitContext context = null)
    {
        return sqlArrayIndexExpression;
    }
    public virtual SqlExpression VisitSqlArraySliceExpression(SqlArraySliceExpression sqlArraySliceExpression, VisitContext context = null)
    {
        return sqlArraySliceExpression;
    }
    public virtual SqlExpression VisitSqlAtTimeZoneExpression(SqlAtTimeZoneExpression sqlAtTimeZoneExpression, VisitContext context = null)
    {
        return sqlAtTimeZoneExpression;
    }
    public virtual SqlExpression VisitSqlBetweenAndExpression(SqlBetweenAndExpression sqlBetweenAndExpression, VisitContext context = null)
    {
        return sqlBetweenAndExpression;
    }
    public virtual SqlExpression VisitSqlBinaryExpression(SqlBinaryExpression sqlBinaryExpression, VisitContext context = null)
    {
        return sqlBinaryExpression;
    }
    public virtual SqlExpression VisitSqlBoolExpression(SqlBoolExpression sqlBoolExpression, VisitContext context = null)
    {
        return sqlBoolExpression;
    }
    public virtual SqlExpression VisitSqlCaseExpression(SqlCaseExpression sqlCaseExpression, VisitContext context = null)
    {
        return sqlCaseExpression;
    }
    public virtual SqlExpression VisitSqlCaseItemExpression(SqlCaseItemExpression sqlCaseItemExpression, VisitContext context = null)
    {
        return sqlCaseItemExpression;
    }
    public virtual SqlExpression VisitSqlCollateExpression(SqlCollateExpression sqlCollateExpression, VisitContext context = null)
    {
        return sqlCollateExpression;
    }
    public virtual SqlExpression VisitSqlConnectByExpression(SqlConnectByExpression sqlConnectByExpression, VisitContext context = null)
    {
        return sqlConnectByExpression;
    }
    public virtual SqlExpression VisitSqlDeleteExpression(SqlDeleteExpression sqlDeleteExpression, VisitContext context = null)
    {
        return sqlDeleteExpression;
    }
    public virtual SqlExpression VisitSqlExistsExpression(SqlExistsExpression sqlExistsExpression, VisitContext context = null)
    {
        return sqlExistsExpression;
    }
    public virtual SqlExpression VisitSqlFunctionCallExpression(SqlFunctionCallExpression sqlFunctionCallExpression, VisitContext context = null)
    {
        return sqlFunctionCallExpression;
    }
    public virtual SqlExpression VisitSqlGroupByExpression(SqlGroupByExpression sqlGroupByExpression, VisitContext context = null)
    {
        return sqlGroupByExpression;
    }
    public virtual SqlExpression VisitSqlHintExpression(SqlHintExpression sqlHintExpression, VisitContext context = null)
    {
        return sqlHintExpression;
    }
    public virtual SqlExpression VisitSqlIdentifierExpression(SqlIdentifierExpression sqlIdentifierExpression, VisitContext context = null)
    {
        return sqlIdentifierExpression;
    }
    public virtual SqlExpression VisitSqlInExpression(SqlInExpression sqlInExpression, VisitContext context = null)
    {
        return sqlInExpression;
    }
    public virtual SqlExpression VisitSqlInsertExpression(SqlInsertExpression sqlInsertExpression, VisitContext context = null)
    {
        return sqlInsertExpression;
    }
    public virtual SqlExpression VisitSqlIntervalExpression(SqlIntervalExpression sqlIntervalExpression, VisitContext context = null)
    {
        return sqlIntervalExpression;
    }
    public virtual SqlExpression VisitSqlJoinTableExpression(SqlJoinTableExpression sqlJoinTableExpression, VisitContext context = null)
    {
        return sqlJoinTableExpression;
    }
    public virtual SqlExpression VisitSqlLimitExpression(SqlLimitExpression sqlLimitExpression, VisitContext context = null)
    {
        return sqlLimitExpression;
    }
    public virtual SqlExpression VisitSqlNotExpression(SqlNotExpression sqlNotExpression, VisitContext context = null)
    {
        return sqlNotExpression;
    }
    public virtual SqlExpression VisitSqlNullExpression(SqlNullExpression sqlNullExpression, VisitContext context = null)
    {
        return sqlNullExpression;
    }
    public virtual SqlExpression VisitSqlNumberExpression(SqlNumberExpression sqlNumberExpression, VisitContext context = null)
    {
        return sqlNumberExpression;
    }
    public virtual SqlExpression VisitSqlOrderByExpression(SqlOrderByExpression sqlOrderByExpression, VisitContext context = null)
    {
        return sqlOrderByExpression;
    }
    public virtual SqlExpression VisitSqlOrderByItemExpression(SqlOrderByItemExpression sqlOrderByItemExpression, VisitContext context = null)
    {
        return sqlOrderByItemExpression;
    }
    public virtual SqlExpression VisitSqlOverExpression(SqlOverExpression sqlOverExpression, VisitContext context = null)
    {
        return sqlOverExpression;
    }
    public virtual SqlExpression VisitSqlPartitionByExpression(SqlPartitionByExpression sqlPartitionByExpression, VisitContext context = null)
    {
        return sqlPartitionByExpression;
    }
    public virtual SqlExpression VisitSqlPivotTableExpression(SqlPivotTableExpression sqlPivotTableExpression, VisitContext context = null)
    {
        return sqlPivotTableExpression;
    }
    public virtual SqlExpression VisitSqlPropertyExpression(SqlPropertyExpression sqlPropertyExpression, VisitContext context = null)
    {
        return sqlPropertyExpression;
    }
    public virtual SqlExpression VisitSqlReferenceTableExpression(SqlReferenceTableExpression sqlReferenceTableExpression, VisitContext context = null)
    {
        return sqlReferenceTableExpression;
    }
    public virtual SqlExpression VisitSqlRegexExpression(SqlRegexExpression sqlRegexExpression, VisitContext context = null)
    {
        return sqlRegexExpression;
    }
    public virtual SqlExpression VisitSqlReturningExpression(SqlReturningExpression sqlReturningExpression, VisitContext context = null)
    {
        return sqlReturningExpression;
    }
    public virtual SqlExpression VisitSqlSelectExpression(SqlSelectExpression sqlSelectExpression, VisitContext context = null)
    {
        return sqlSelectExpression;
    }
    public virtual SqlExpression VisitSqlSelectItemExpression(SqlSelectItemExpression sqlSelectItemExpression, VisitContext context = null)
    {
        return sqlSelectItemExpression;
    }
    public virtual SqlExpression VisitSqlSelectQueryExpression(SqlSelectQueryExpression sqlSelectQueryExpression, VisitContext context = null)
    {
        return sqlSelectQueryExpression;
    }
    public virtual SqlExpression VisitSqlStringExpression(SqlStringExpression sqlStringExpression, VisitContext context = null)
    {
        return sqlStringExpression;
    }
    public virtual SqlExpression VisitSqlTableExpression(SqlTableExpression sqlTableExpression, VisitContext context = null)
    {
        return sqlTableExpression;
    }
    public virtual SqlExpression VisitSqlTimeUnitExpression(SqlTimeUnitExpression sqlTimeUnitExpression, VisitContext context = null)
    {
        return sqlTimeUnitExpression;
    }
    public virtual SqlExpression VisitSqlTopExpression(SqlTopExpression sqlTopExpression, VisitContext context = null)
    {
        return sqlTopExpression;
    }
    public virtual SqlExpression VisitSqlUnionQueryExpression(SqlUnionQueryExpression sqlUnionQueryExpression, VisitContext context = null)
    {
        return sqlUnionQueryExpression;
    }
    public virtual SqlExpression VisitSqlUpdateExpression(SqlUpdateExpression sqlUpdateExpression, VisitContext context = null)
    {
        return sqlUpdateExpression;
    }
    public virtual SqlExpression VisitSqlVariableExpression(SqlVariableExpression sqlVariableExpression, VisitContext context = null)
    {
        return sqlVariableExpression;
    }
    public virtual SqlExpression VisitSqlWithinGroupExpression(SqlWithinGroupExpression sqlWithinGroupExpression, VisitContext context = null)
    {
        return sqlWithinGroupExpression;
    }
    public virtual SqlExpression VisitSqlWithSubQueryExpression(SqlWithSubQueryExpression sqlWithSubQueryExpression, VisitContext context = null)
    {
        return sqlWithSubQueryExpression;
    }
}