using SqlParser.Net.Ast.Expression;

/// <summary>
/// Automatically generated by testHelper
/// </summary>
public class BaseAstVisitor : IAstVisitor
{
    public virtual void VisitSqlAllColumnExpression(SqlAllColumnExpression sqlAllColumnExpression)
    {

    }
    public virtual void VisitSqlAllExpression(SqlAllExpression sqlAllExpression)
    {

    }
    public virtual void VisitSqlAnyExpression(SqlAnyExpression sqlAnyExpression)
    {

    }
    public virtual void VisitSqlAtTimeZoneExpression(SqlAtTimeZoneExpression sqlAtTimeZoneExpression)
    {

    }
    public virtual void VisitSqlBetweenAndExpression(SqlBetweenAndExpression sqlBetweenAndExpression)
    {

    }
    public virtual void VisitSqlBinaryExpression(SqlBinaryExpression sqlBinaryExpression)
    {

    }
    public virtual void VisitSqlBoolExpression(SqlBoolExpression sqlBoolExpression)
    {

    }
    public virtual void VisitSqlCaseExpression(SqlCaseExpression sqlCaseExpression)
    {

    }
    public virtual void VisitSqlCaseItemExpression(SqlCaseItemExpression sqlCaseItemExpression)
    {

    }
    public virtual void VisitSqlCollateExpression(SqlCollateExpression sqlCollateExpression)
    {

    }
    public virtual void VisitSqlConnectByExpression(SqlConnectByExpression sqlConnectByExpression)
    {

    }
    public virtual void VisitSqlDeleteExpression(SqlDeleteExpression sqlDeleteExpression)
    {

    }
    public virtual void VisitSqlExistsExpression(SqlExistsExpression sqlExistsExpression)
    {

    }
    public virtual void VisitSqlFunctionCallExpression(SqlFunctionCallExpression sqlFunctionCallExpression)
    {

    }
    public virtual void VisitSqlGroupByExpression(SqlGroupByExpression sqlGroupByExpression)
    {

    }
    public virtual void VisitSqlHintExpression(SqlHintExpression sqlHintExpression)
    {

    }
    public virtual void VisitSqlIdentifierExpression(SqlIdentifierExpression sqlIdentifierExpression)
    {

    }
    public virtual void VisitSqlInExpression(SqlInExpression sqlInExpression)
    {

    }
    public virtual void VisitSqlInsertExpression(SqlInsertExpression sqlInsertExpression)
    {

    }
    public virtual void VisitSqlIntervalExpression(SqlIntervalExpression sqlIntervalExpression)
    {

    }
    public virtual void VisitSqlJoinTableExpression(SqlJoinTableExpression sqlJoinTableExpression)
    {

    }
    public virtual void VisitSqlLimitExpression(SqlLimitExpression sqlLimitExpression)
    {

    }
    public virtual void VisitSqlNotExpression(SqlNotExpression sqlNotExpression)
    {

    }
    public virtual void VisitSqlNullExpression(SqlNullExpression sqlNullExpression)
    {

    }
    public virtual void VisitSqlNumberExpression(SqlNumberExpression sqlNumberExpression)
    {

    }
    public virtual void VisitSqlOrderByExpression(SqlOrderByExpression sqlOrderByExpression)
    {

    }
    public virtual void VisitSqlOrderByItemExpression(SqlOrderByItemExpression sqlOrderByItemExpression)
    {

    }
    public virtual void VisitSqlOverExpression(SqlOverExpression sqlOverExpression)
    {

    }
    public virtual void VisitSqlPartitionByExpression(SqlPartitionByExpression sqlPartitionByExpression)
    {

    }
    public virtual void VisitSqlPivotTableExpression(SqlPivotTableExpression sqlPivotTableExpression)
    {

    }
    public virtual void VisitSqlPropertyExpression(SqlPropertyExpression sqlPropertyExpression)
    {

    }
    public virtual void VisitSqlReferenceTableExpression(SqlReferenceTableExpression sqlReferenceTableExpression)
    {

    }
    public virtual void VisitSqlRegexExpression(SqlRegexExpression sqlRegexExpression)
    {

    }

    public virtual void VisitSqlReturningExpression(SqlReturningExpression sqlReturningExpression)
    {
        
    }

    public virtual void VisitSqlSelectExpression(SqlSelectExpression sqlSelectExpression)
    {

    }
    public virtual void VisitSqlSelectItemExpression(SqlSelectItemExpression sqlSelectItemExpression)
    {

    }
    public virtual void VisitSqlSelectQueryExpression(SqlSelectQueryExpression sqlSelectQueryExpression)
    {

    }
    public virtual void VisitSqlStringExpression(SqlStringExpression sqlStringExpression)
    {

    }
    public virtual void VisitSqlTableExpression(SqlTableExpression sqlTableExpression)
    {

    }
    public virtual void VisitSqlTimeUnitExpression(SqlTimeUnitExpression sqlTimeUnitExpression)
    {

    }
    public virtual void VisitSqlTopExpression(SqlTopExpression sqlTopExpression)
    {

    }
    public virtual void VisitSqlUnionQueryExpression(SqlUnionQueryExpression sqlUnionQueryExpression)
    {

    }
    public virtual void VisitSqlUpdateExpression(SqlUpdateExpression sqlUpdateExpression)
    {

    }
    public virtual void VisitSqlVariableExpression(SqlVariableExpression sqlVariableExpression)
    {

    }
    public virtual void VisitSqlWithinGroupExpression(SqlWithinGroupExpression sqlWithinGroupExpression)
    {

    }
    public virtual void VisitSqlWithSubQueryExpression(SqlWithSubQueryExpression sqlWithSubQueryExpression)
    {

    }
}