using SqlParser.Net.Ast.Expression;

/// <summary>
/// Automatically generated by testHelper
/// </summary>
public class BaseAstVisitor : IAstVisitor
{
    public virtual SqlExpression VisitSqlAllColumnExpression(SqlAllColumnExpression sqlAllColumnExpression)
    {
        return sqlAllColumnExpression;
    }
    public virtual SqlExpression VisitSqlAllExpression(SqlAllExpression sqlAllExpression)
    {
        return sqlAllExpression;
    }
    public virtual SqlExpression VisitSqlAnyExpression(SqlAnyExpression sqlAnyExpression)
    {
        return sqlAnyExpression;
    }
    public virtual SqlExpression VisitSqlArrayExpression(SqlArrayExpression sqlArrayExpression)
    {
        return sqlArrayExpression;
    }
    public virtual SqlExpression VisitSqlArrayIndexExpression(SqlArrayIndexExpression sqlArrayIndexExpression)
    {
        return sqlArrayIndexExpression;
    }
    public virtual SqlExpression VisitSqlArraySliceExpression(SqlArraySliceExpression sqlArraySliceExpression)
    {
        return sqlArraySliceExpression;
    }
    public virtual SqlExpression VisitSqlAtTimeZoneExpression(SqlAtTimeZoneExpression sqlAtTimeZoneExpression)
    {
        return sqlAtTimeZoneExpression;
    }
    public virtual SqlExpression VisitSqlBetweenAndExpression(SqlBetweenAndExpression sqlBetweenAndExpression)
    {
        return sqlBetweenAndExpression;
    }
    public virtual SqlExpression VisitSqlBinaryExpression(SqlBinaryExpression sqlBinaryExpression)
    {
        return sqlBinaryExpression;
    }
    public virtual SqlExpression VisitSqlBoolExpression(SqlBoolExpression sqlBoolExpression)
    {
        return sqlBoolExpression;
    }
    public virtual SqlExpression VisitSqlCaseExpression(SqlCaseExpression sqlCaseExpression)
    {
        return sqlCaseExpression;
    }
    public virtual SqlExpression VisitSqlCaseItemExpression(SqlCaseItemExpression sqlCaseItemExpression)
    {
        return sqlCaseItemExpression;
    }
    public virtual SqlExpression VisitSqlCollateExpression(SqlCollateExpression sqlCollateExpression)
    {
        return sqlCollateExpression;
    }
    public virtual SqlExpression VisitSqlConnectByExpression(SqlConnectByExpression sqlConnectByExpression)
    {
        return sqlConnectByExpression;
    }
    public virtual SqlExpression VisitSqlDeleteExpression(SqlDeleteExpression sqlDeleteExpression)
    {
        return sqlDeleteExpression;
    }
    public virtual SqlExpression VisitSqlExistsExpression(SqlExistsExpression sqlExistsExpression)
    {
        return sqlExistsExpression;
    }
    public virtual SqlExpression VisitSqlFunctionCallExpression(SqlFunctionCallExpression sqlFunctionCallExpression)
    {
        return sqlFunctionCallExpression;
    }
    public virtual SqlExpression VisitSqlGroupByExpression(SqlGroupByExpression sqlGroupByExpression)
    {
        return sqlGroupByExpression;
    }
    public virtual SqlExpression VisitSqlHintExpression(SqlHintExpression sqlHintExpression)
    {
        return sqlHintExpression;
    }
    public virtual SqlExpression VisitSqlIdentifierExpression(SqlIdentifierExpression sqlIdentifierExpression)
    {
        return sqlIdentifierExpression;
    }
    public virtual SqlExpression VisitSqlInExpression(SqlInExpression sqlInExpression)
    {
        return sqlInExpression;
    }
    public virtual SqlExpression VisitSqlInsertExpression(SqlInsertExpression sqlInsertExpression)
    {
        return sqlInsertExpression;
    }
    public virtual SqlExpression VisitSqlIntervalExpression(SqlIntervalExpression sqlIntervalExpression)
    {
        return sqlIntervalExpression;
    }
    public virtual SqlExpression VisitSqlJoinTableExpression(SqlJoinTableExpression sqlJoinTableExpression)
    {
        return sqlJoinTableExpression;
    }
    public virtual SqlExpression VisitSqlLimitExpression(SqlLimitExpression sqlLimitExpression)
    {
        return sqlLimitExpression;
    }
    public virtual SqlExpression VisitSqlNotExpression(SqlNotExpression sqlNotExpression)
    {
        return sqlNotExpression;
    }
    public virtual SqlExpression VisitSqlNullExpression(SqlNullExpression sqlNullExpression)
    {
        return sqlNullExpression;
    }
    public virtual SqlExpression VisitSqlNumberExpression(SqlNumberExpression sqlNumberExpression)
    {
        return sqlNumberExpression;
    }
    public virtual SqlExpression VisitSqlOrderByExpression(SqlOrderByExpression sqlOrderByExpression)
    {
        return sqlOrderByExpression;
    }
    public virtual SqlExpression VisitSqlOrderByItemExpression(SqlOrderByItemExpression sqlOrderByItemExpression)
    {
        return sqlOrderByItemExpression;
    }
    public virtual SqlExpression VisitSqlOverExpression(SqlOverExpression sqlOverExpression)
    {
        return sqlOverExpression;
    }
    public virtual SqlExpression VisitSqlPartitionByExpression(SqlPartitionByExpression sqlPartitionByExpression)
    {
        return sqlPartitionByExpression;
    }
    public virtual SqlExpression VisitSqlPivotTableExpression(SqlPivotTableExpression sqlPivotTableExpression)
    {
        return sqlPivotTableExpression;
    }
    public virtual SqlExpression VisitSqlPropertyExpression(SqlPropertyExpression sqlPropertyExpression)
    {
        return sqlPropertyExpression;
    }
    public virtual SqlExpression VisitSqlReferenceTableExpression(SqlReferenceTableExpression sqlReferenceTableExpression)
    {
        return sqlReferenceTableExpression;
    }
    public virtual SqlExpression VisitSqlRegexExpression(SqlRegexExpression sqlRegexExpression)
    {
        return sqlRegexExpression;
    }
    public virtual SqlExpression VisitSqlReturningExpression(SqlReturningExpression sqlReturningExpression)
    {
        return sqlReturningExpression;
    }
    public virtual SqlExpression VisitSqlSelectExpression(SqlSelectExpression sqlSelectExpression)
    {
        return sqlSelectExpression;
    }
    public virtual SqlExpression VisitSqlSelectItemExpression(SqlSelectItemExpression sqlSelectItemExpression)
    {
        return sqlSelectItemExpression;
    }
    public virtual SqlExpression VisitSqlSelectQueryExpression(SqlSelectQueryExpression sqlSelectQueryExpression)
    {
        return sqlSelectQueryExpression;
    }
    public virtual SqlExpression VisitSqlStringExpression(SqlStringExpression sqlStringExpression)
    {
        return sqlStringExpression;
    }
    public virtual SqlExpression VisitSqlTableExpression(SqlTableExpression sqlTableExpression)
    {
        return sqlTableExpression;
    }
    public virtual SqlExpression VisitSqlTimeUnitExpression(SqlTimeUnitExpression sqlTimeUnitExpression)
    {
        return sqlTimeUnitExpression;
    }
    public virtual SqlExpression VisitSqlTopExpression(SqlTopExpression sqlTopExpression)
    {
        return sqlTopExpression;
    }
    public virtual SqlExpression VisitSqlUnionQueryExpression(SqlUnionQueryExpression sqlUnionQueryExpression)
    {
        return sqlUnionQueryExpression;
    }
    public virtual SqlExpression VisitSqlUpdateExpression(SqlUpdateExpression sqlUpdateExpression)
    {
        return sqlUpdateExpression;
    }
    public virtual SqlExpression VisitSqlVariableExpression(SqlVariableExpression sqlVariableExpression)
    {
        return sqlVariableExpression;
    }
    public virtual SqlExpression VisitSqlWithinGroupExpression(SqlWithinGroupExpression sqlWithinGroupExpression)
    {
        return sqlWithinGroupExpression;
    }
    public virtual SqlExpression VisitSqlWithSubQueryExpression(SqlWithSubQueryExpression sqlWithSubQueryExpression)
    {
        return sqlWithSubQueryExpression;
    }
}