using SqlParser.Net.Ast.Expression;

/// <summary>
/// Automatically generated by testHelper
/// </summary>
public interface IAstVisitor
{
    SqlExpression VisitSqlAllColumnExpression(SqlAllColumnExpression sqlAllColumnExpression);
    SqlExpression VisitSqlAllExpression(SqlAllExpression sqlAllExpression);
    SqlExpression VisitSqlAnyExpression(SqlAnyExpression sqlAnyExpression);
    SqlExpression VisitSqlArrayExpression(SqlArrayExpression sqlArrayExpression);
    SqlExpression VisitSqlArrayIndexExpression(SqlArrayIndexExpression sqlArrayIndexExpression);
    SqlExpression VisitSqlArraySliceExpression(SqlArraySliceExpression sqlArraySliceExpression);
    SqlExpression VisitSqlAtTimeZoneExpression(SqlAtTimeZoneExpression sqlAtTimeZoneExpression);
    SqlExpression VisitSqlBetweenAndExpression(SqlBetweenAndExpression sqlBetweenAndExpression);
    SqlExpression VisitSqlBinaryExpression(SqlBinaryExpression sqlBinaryExpression);
    SqlExpression VisitSqlBoolExpression(SqlBoolExpression sqlBoolExpression);
    SqlExpression VisitSqlCaseExpression(SqlCaseExpression sqlCaseExpression);
    SqlExpression VisitSqlCaseItemExpression(SqlCaseItemExpression sqlCaseItemExpression);
    SqlExpression VisitSqlCollateExpression(SqlCollateExpression sqlCollateExpression);
    SqlExpression VisitSqlConnectByExpression(SqlConnectByExpression sqlConnectByExpression);
    SqlExpression VisitSqlDeleteExpression(SqlDeleteExpression sqlDeleteExpression);
    SqlExpression VisitSqlExistsExpression(SqlExistsExpression sqlExistsExpression);
    SqlExpression VisitSqlFunctionCallExpression(SqlFunctionCallExpression sqlFunctionCallExpression);
    SqlExpression VisitSqlGroupByExpression(SqlGroupByExpression sqlGroupByExpression);
    SqlExpression VisitSqlHintExpression(SqlHintExpression sqlHintExpression);
    SqlExpression VisitSqlIdentifierExpression(SqlIdentifierExpression sqlIdentifierExpression);
    SqlExpression VisitSqlInExpression(SqlInExpression sqlInExpression);
    SqlExpression VisitSqlInsertExpression(SqlInsertExpression sqlInsertExpression);
    SqlExpression VisitSqlIntervalExpression(SqlIntervalExpression sqlIntervalExpression);
    SqlExpression VisitSqlJoinTableExpression(SqlJoinTableExpression sqlJoinTableExpression);
    SqlExpression VisitSqlLimitExpression(SqlLimitExpression sqlLimitExpression);
    SqlExpression VisitSqlNotExpression(SqlNotExpression sqlNotExpression);
    SqlExpression VisitSqlNullExpression(SqlNullExpression sqlNullExpression);
    SqlExpression VisitSqlNumberExpression(SqlNumberExpression sqlNumberExpression);
    SqlExpression VisitSqlOrderByExpression(SqlOrderByExpression sqlOrderByExpression);
    SqlExpression VisitSqlOrderByItemExpression(SqlOrderByItemExpression sqlOrderByItemExpression);
    SqlExpression VisitSqlOverExpression(SqlOverExpression sqlOverExpression);
    SqlExpression VisitSqlPartitionByExpression(SqlPartitionByExpression sqlPartitionByExpression);
    SqlExpression VisitSqlPivotTableExpression(SqlPivotTableExpression sqlPivotTableExpression);
    SqlExpression VisitSqlPropertyExpression(SqlPropertyExpression sqlPropertyExpression);
    SqlExpression VisitSqlReferenceTableExpression(SqlReferenceTableExpression sqlReferenceTableExpression);
    SqlExpression VisitSqlRegexExpression(SqlRegexExpression sqlRegexExpression);
    SqlExpression VisitSqlReturningExpression(SqlReturningExpression sqlReturningExpression);
    SqlExpression VisitSqlSelectExpression(SqlSelectExpression sqlSelectExpression);
    SqlExpression VisitSqlSelectItemExpression(SqlSelectItemExpression sqlSelectItemExpression);
    SqlExpression VisitSqlSelectQueryExpression(SqlSelectQueryExpression sqlSelectQueryExpression);
    SqlExpression VisitSqlStringExpression(SqlStringExpression sqlStringExpression);
    SqlExpression VisitSqlTableExpression(SqlTableExpression sqlTableExpression);
    SqlExpression VisitSqlTimeUnitExpression(SqlTimeUnitExpression sqlTimeUnitExpression);
    SqlExpression VisitSqlTopExpression(SqlTopExpression sqlTopExpression);
    SqlExpression VisitSqlUnionQueryExpression(SqlUnionQueryExpression sqlUnionQueryExpression);
    SqlExpression VisitSqlUpdateExpression(SqlUpdateExpression sqlUpdateExpression);
    SqlExpression VisitSqlVariableExpression(SqlVariableExpression sqlVariableExpression);
    SqlExpression VisitSqlWithinGroupExpression(SqlWithinGroupExpression sqlWithinGroupExpression);
    SqlExpression VisitSqlWithSubQueryExpression(SqlWithSubQueryExpression sqlWithSubQueryExpression);
}