DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
                           customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           customer_name VARCHAR(100) NOT NULL,
                           city VARCHAR(50),
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
                        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id BIGINT NOT NULL,
                        order_no VARCHAR(50) NOT NULL UNIQUE,
                        amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
                        order_status VARCHAR(20) NOT NULL DEFAULT 'PAID',
                        order_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT fk_orders_customer
                            FOREIGN KEY (customer_id)
                                REFERENCES customers(customer_id)
);

CREATE INDEX idx_orders_customer_time
    ON orders (customer_id, order_time DESC);


INSERT INTO customers (customer_name, city)
VALUES
    ('张三', '北京'),
    ('李四', '上海'),
    ('王五', '广州'),
    ('赵六', '深圳');

INSERT INTO orders
(customer_id, order_no, amount, order_status, order_time)
VALUES
    (1, 'ORD20240001', 100.00, 'PAID',    '2024-01-10 10:00:00'),
    (1, 'ORD20240002', 250.00, 'PAID',    '2024-02-15 12:00:00'),
    (1, 'ORD20240003', 180.00, 'CANCEL', '2024-03-01 09:00:00'),

    (2, 'ORD20240004', 520.00, 'PAID',    '2024-01-20 14:00:00'),
    (2, 'ORD20240005', 80.00,  'PAID',    '2024-03-10 16:00:00'),

    (3, 'ORD20240006', 300.00, 'PAID',    '2024-02-01 08:00:00');



SELECT
    c.customer_id,
    c.customer_name,
    latest_order.order_id,
    latest_order.order_no,
    latest_order.amount,
    latest_order.order_time
FROM customers c
         CROSS JOIN LATERAL (
    SELECT
        o.order_id,
        o.order_no,
        o.amount,
        o.order_time
    FROM orders o
    WHERE o.customer_id = c.customer_id
      AND o.order_status = 'PAID'
    ORDER BY o.order_time DESC, o.order_id DESC
        LIMIT 1
) AS latest_order
ORDER BY c.customer_id;